section_order: 
  - home
  - us
  - event
  - registry
  - travel
  - accomodations
carousel_images: 
  - carousel-2016-05-21
  - carousel-2017-07-08
  - carousel-2017-11-16
  - carousel-2014-06-01
  - carousel-2014-10-17
  - carousel-2015-05-03
  - carousel-2015-06-14
  - carousel-2015-07-03
  - carousel-2015-11-11
  - carousel-2016-01-11
  - carousel-2016-01-14
  - carousel-2016-05-21
  - carousel-2016-07-15
  - carousel-2016-07-16
  - carousel-2016-08-15
  - carousel-2016-09-03
  - carousel-2016-09-12
  - carousel-2016-10-29
  - carousel-2016-11-12
  - carousel-2017-04-21
  - carousel-2017-06-21
  - carousel-2017-07-08
  - carousel-2017-09-03
  - carousel-2017-11-12
  - carousel-2017-11-14
  - carousel-2017-11-16
